### ISSUE TITLE
Requesting Windows 7 support for DX12 feature level 11_0 GPUs

### ISSUE THREAD

**Issue by oceanbandit** [tuffee88/d3d12ProxyEdrDx11_0#1]
It seems this fix only works on machines with Operating Systems like Windows 10 that have DX12 support.

**Comment by tuffee88** [comment]
This should work on Windows 7 too - provided you would be able to run Elden Ring on Windows 7 in the first place (not supported) :-)
-> If you're on Windows 7, you might want to try one of the more popular Windows 7 mods (https://www.nexusmods.com/eldenring/mods/12) first
-> If you get the white screen of death and suspect it's your graphics cards DX12 feature level support (remember to try all common fixes first) feel free to try this one - there should be nothing Windows 10 specific about it.

**Comment by tuffee88** [comment]
Using this with windows 7 (+win7 patched eldenring.exe and vkd3d for d3d12 support on win7) indeed works 
-> There are several success reports at: https://www.nexusmods.com/eldenring/mods/12?tab=posts&BH=1 so I'm closing this issue :-)
