### ISSUE TITLE
Fog not properly rendered

### ISSUE THREAD

**Issue by peppemartincastro** [tuffee88/d3d12ProxyEdrDx11_0#10]
[gtx_660_vs_gtx_970.zip](https://github.com/tuffee88/d3d12ProxyEdrDx11_0/files/8204836/gtx_660_vs_gtx_970.zip)

I'd like to report that the game is running with reasonable framerates on both my gtx 660 and tesla k20Xm (gtx titan equivalent) thanks to this fix, but I've encountered some issues in how the fog is rendered while using the kepler cards. As you can se from the pictures there's clearly some fog missing on the gtx 660 if you compare it to the gtx 970 (which supports dx12 feature level 12_1 and thus runs the game natively). Another intresting thing imho is that even if you run the game on the gtx 970 with the modified d3d12 file the fog is still correctly rendered. I've also noticed a bit of flickering on the kepler cards.

P.S. If you are worried about spoilers I've taken the pictures on top of the first big tower, the one near the castle, and I've removed all equipment from my character.

**Comment by tuffee88** [comment]
Glad to see a fellow Tesla user here (I'm using a K40m) !  
Did you use the same graphics settings on all cards ?

If so this could be due to driver differences - given the fact that the fog is rendered on Kepler cards (albeit thinner), or maybe some actual DX12 feature that's not working on Kepler. I'm sorry but this is beyond the scope of this project - as this requires more analysis and probably won't be fixed with simple function call tweaks.

**Comment by peppemartincastro** [comment]
Same graphical settings (all high, DOF and Blur disabled). I will try the 970 with the same driver version of the 660 and I'll let you know

**Comment by tuffee88** [comment]
Even using the same driver probably won't help - I'm sure the same driver version has different code paths to cater for different architectures, but there is no harm in trying :-)

**Comment by peppemartincastro** [comment]
Tested the 970 with 472.12 drivers (same as the 660) with and without the custom d3d12, the fog was rendered properly in both cases. I guess you were right, hopefully someone will figure out how to solve this problem. Thank you for your quick replies and especially for this fix, I'm sure it will be helpful to many people regardless of this little fog issue.

**Comment by tuffee88** [comment]
No worries, thanks for the feedback ! Closing as this is a driver/feature related issue.
