### ISSUE TITLE
Win10 Feature Level less than 1909 does not have D3D12Core.dll

### ISSUE THREAD

**Issue by V1KZZ** [tuffee88/d3d12ProxyEdrDx11_0#12]
I think the reason may be is because they do not have Agility SDK support.

Is there an alternative solution to bypass this?
Have tried taking the Core dll from a separate Laptop I own however did not work.

**Comment by tuffee88** [comment]
This is interesting, if D3D12Core.dll is not available in windows/system32 but d3d12.dll this should just work fine without it.

Please delete the D3D12Core.dll from the game folder (the one from the different laptop), and copy + rename the existing d3d12.dll from windows/system32.dll (rename to d3d12_original.dll) and retry.

Please let me know if this works for you - and if it doesn't please attach the output from DebugView so I can have a look if this is related to the proxy dll or a different issue.

**Comment by V1KZZ** [comment]
Worked like a charm! Nice to know that there's a fix:

Just to confirm I'm on AMD Radeon HD 7950, Win10 1903
