### ISSUE TITLE
D3d12core.dll

### ISSUE THREAD

**Issue by Andrade2244** [tuffee88/d3d12ProxyEdrDx11_0#13]
Hi. Congrats for the fix. I tried it although it didn't fix my problem cause i'm having a slighty different issue. I have an intel card that supports dx12 level 12.1 and i'm able to get to the character creation menu  but when i try to get in game it crashes to desktop while loading. In the event viewer it says there is fault in the module d3d12core.dll. I'm on windows 11 by the way. In another similar laptop that i have with another model of intel hd it launches fine but in this one it always crash. Everything is updated and i've run plenty of dx12 only games. Do you have a clue on what can be the issue?

**Comment by tuffee88** [comment]
Given the spotty support track record of intel's graphics drivers you'll probably have to wait until an driver update or patch for elden ring  is released (if this happens) - Sorry, I won't be able to help you with this :-)
