### ISSUE TITLE
İnvisible enemies

### ISSUE THREAD

**Issue by GorkemKurter** [tuffee88/d3d12ProxyEdrDx11_0#14]
Somehow enemies are "invisible".Do you have any fix?Thank you.

Known methods does not work(like updating drivers...)

**Comment by tuffee88** [comment]
Sorry, the invisible enemy problem is not directly related to this (happens with newer graphics cards, too) - you'll probably have to wait for a game patch/update to get this fixed.

**Comment by GigaEgo** [comment]
https://www.nexusmods.com/eldenring/mods/109?tab=description a fix
