### ISSUE TITLE
I can confirm that this works on Assassin's Creed Valhalla using GTX 850m.

### ISSUE THREAD

**Issue by Sitis133** [tuffee88/d3d12ProxyEdrDx11_0#16]
mojmass
Hello, please post the required file in the repository ;)

**Comment by mojmass** [comment]
Made a fork
download here 
https://github.com/mojmass/d3d12ProxyEdrDx11_0/releases/tag/v0.2

**Comment by Sitis133** [comment]
Thank you very much 👍

**Comment by Sitis133** [comment]
tuffee88, I am infinitely grateful to you and many other people are very grateful to you. :)
Thank you very muc  
sry for my other issue, im a noob here ;)

**Comment by Sitis133** [comment]
tuffee88, please, make the same fix for Death Stranding. :)

**Comment by tuffee88** [comment]
> tuffee88, please, make the same fix for Death Stranding. :)

I have one report that this works for Death Stranding (750ti)- please have a try and let me know if this works for you, too.
