### ISSUE TITLE
Elden Ring

### ISSUE THREAD

**Issue by Bizzaerro** [tuffee88/d3d12ProxyEdrDx11_0#17]
Can confirm elden ring works on r7 series without any problems

**Comment by tuffee88** [comment]
Thanks for the feedback ! Which card are you using exactly ?

**Comment by Bizzaerro** [comment]
r7 370. And it is running well with gfx tweaks . Thanks for your work.

**Comment by tuffee88** [comment]
Great, glad to hear its working for you ! I'll add this card to the README :-)

**Comment by mxthewarrior** [comment]
Can you help me? I have a r7 370 too, but my games crashesd :c

**Comment by Bizzaerro** [comment]
Well , all i did was same things in readme file. Copied dll files and rename them. What is your problem ? white screen and crash ?
