### ISSUE TITLE
Not an issue. Playing on a 680 GTX

### ISSUE THREAD

**Issue by Exhore** [tuffee88/d3d12ProxyEdrDx11_0#19]
Game runs absolutely fine. Played like 15 hours ~. I'm impressed someone could pull this off. You're a genius!

Mid graphics upscaling to 1080p avg 40 fps, playable. Closed areas 60 constant fps.

Rest of the pc: i5 8600k @4,5 ghz, 16 gb ddr4 3400 mhz on a samsung nvme ssd.

**Comment by tuffee88** [comment]
Glad to hear that, thanks for the feedback !
