### ISSUE TITLE
Crash ingame R7 370

### ISSUE THREAD

**Issue by mxthewarrior** [tuffee88/d3d12ProxyEdrDx11_0#20]
I have constans crash with a R7 370 2gb, the graphic card have dx 12 (11_1), can it have related?
Sorry about my english tho.

**Comment by tuffee88** [comment]
It could be related, but I don't have many reports from AMD users so this could also be just a driver or game optimization problem.

Did you try to update Windows + latest graphics drivers and reduced graphics settings (so you get below 2 GB Vram usage) ? 

Btw. Some Nvidia Cards with DX12 feature Level 11_0 exhibit some screen flickering or incorrect fog rendering but in general the game is playable with all major features intact and rarely crashes (not more than with newer gpus).

**Comment by tuffee88** [comment]
Please also try running this via Vulkan via vkd3d-proton (you can grab ready-made Windows binaries at: https://www.nexusmods.com/eldenring/mods/12), as AMD seems to have better Vulkan support.

**Comment by mxthewarrior** [comment]
Hi! Im glad you answer! Im going to try my best to explain myself. 

Well, im running W10 updated, version of elden ring 1.02.3 by PLAZA.
First, thanks to do this dll, im really happy there is people like you doing the gaming worls a better place.
Now, i tried various things, 
First i changed the d3d12.dll to yours, the game launch correctly and i play like 2 hours until first crash.
The crash: game sttuter heavy, freeze, then closes (while sound still playing) and i have an amd crash report that says
"Detectamos que caducó el tiempo de espera del controlador en tu sistema AMD" (idk how to translate it)
Of course i was playing with the lowest config. Im seen in msi afterburner that i getting over 2000 mb of vram usage when crash, maeby there a way to extend the vram to ram to try.

I Tried adding the "oo2core_6_win64.dll", no changes.
Tried so to limit directx feacture to 11_0 with dxcpl, no changes.

My card also show some texture flickering in the groud, that is solved completly if i put the grass on high, but this didnt help with crashes.

Then i reinstall the game in another place and try the Vulkan method, and, it works! But it work slower than dx12, in dx12 i have an 40 fps average with 30 fps drop, and in vulkan i have 30 fps average with 18 fps drop. Ah, and the enemies gets invicible.

Im getting slowly mad with this game, i just want to play but it was very hard.
I going to search about virtually extend vram.

**Comment by tuffee88** [comment]
This seems to be just the standard "AMD GPU driver timeout message" 
-> Very likely a driver issue, sorry but this is nothing that can be fixed with this project. 
I'm puzzled why you could play for hours before the first crash though !

Do you have the newest graphics driver installed ? Did you experience similar problems with other games ? 
Maybe also check your GPU temp, disable any overclocking, ecc.

**Comment by mxthewarrior** [comment]
Okay im going to try different driver version, but yes, im in the lasted driver, but my graphic card hasnt have new support since a year or two.
I didnt have this problem with any other game, maeby i should try install a fresh w10 in a disk and try again.
Gpu temp never rise 70 degrees, and cant overclock it because is a oc version, maeby uderclock could fix it hahahaha.

Well, im going to try a few thing in this days, if i discover some workaround im going to write here.

**Comment by mxthewarrior** [comment]
Oh, and here is the Debugview64 log:

00000001	0.00000000	[6928] Proxy Dll process attach	
00000002	0.00232400	[6928] D3D12CreateDevice-LoadLibrary Result:b2ba0000	
00000003	0.30465961	[6928] Shutdown handler: initalize.	
00000004	0.47863239	[1304] [TRACE] The DiagOutputDir folder is accessible 	
00000005	0.55638790	[6928] D3D12CreateDevice - Proxy function called!	
00000006	0.55724913	[6928] D3D12CreateDevice - Original function address queried	
00000007	0.66715920	[6928] D3D12CreateDevice-CallResult:0	
00000008	0.89095300	[9240] [TRACE] The DiagOutputDir folder is accessible 	
00000009	0.95629621	[1304] Unexpected State	
00000010	0.97558308	[1304] Unexpected State	
00000011	1.59762645	[7808] ************Executable file path is: '	
00000012	1.59764397	[7808] \Device\HarddiskVolume3\Windows\System32\svchost.exe	
00000013	1.59766817	[7808] 	
00000014	1.59768975	[7808] PID=7808	
00000015	1.59770966	[7808] 	
00000016	1.59772897	[7808] ************Trace & dump config file path is: '	
00000017	1.59774840	[7808] C:\Users\boade\AppData\Local\AMDh264Encoder.cfg	
00000018	1.59776819	[7808] '************	
00000019	1.96417201	[7808] 2022-03-14 04:47:29.655      81C [AMFH264AsyncEncoderMF]   Error: ..\..\..\..\..\runtime\src\mft\vceencoder\H264AsyncEncoderMFT.cpp(527):OnSetOutputType(0): failed to set MF_MT_FRAME_RATE set to 30000/1001, HRESULT(0x80070057) 	
00000020	19.56586075	[7808] 2022-03-14 04:47:47.257      1D8 [AMFH264AsyncEncoderMF]   Error: ..\..\..\..\..\runtime\src\mft\vceencoder\H264AsyncEncoderMFT.cpp(527):OnSetOutputType(1): failed to set MF_MT_FRAME_RATE set to 30000/1001, HRESULT(0x80070057) 	
00000021	21.28812408	[7808] 2022-03-14 04:47:48.980     2600 [AMFH264AsyncEncoderMF]   Error: ..\..\..\..\..\runtime\src\mft\vceencoder\H264AsyncEncoderMFT.cpp(527):OnSetOutputType(2): failed to set MF_MT_FRAME_RATE set to 30000/1001, HRESULT(0x80070057) 	
00000022	28.98806000	[4104] "2022-03-14-04:47:56.680 ~~ Registry changed detected."	
00000023	29.05029106	[4104] title:  "RADEON SOFTWARE"	
00000024	29.05162239	[4104] text:  "Presiona %1 para abrir"	
00000025	29.05176353	[4104] hotkey:  "ALT+R"	
00000026	34.00128174	[4104] "2022-03-14-04:48:01.692 ~~ Registry changed detected."	
00000027	34.10289764	[4104] title:  "RADEON SOFTWARE"	
00000028	34.10411835	[4104] text:  ""	
00000029	34.10417175	[4104] hotkey:  "ALT+R"	
00000030	150.84095764	[6928] D3D12: Removing Device.	
00000031	153.57670593	[7808] 2022-03-14 04:50:01.268      4C0 [AMFH264AsyncEncoderMF]   Error: ..\..\..\..\..\runtime\src\mft\vceencoder\H264AsyncEncoderMFT.cpp(527):OnSetOutputType(3): failed to set MF_MT_FRAME_RATE set to 30000/1001, HRESULT(0x80070057) 	
00000032	160.05755615	[7808] 2022-03-14 04:50:07.748     250C [AMFH264AsyncEncoderMF]   Error: ..\..\..\..\..\runtime\src\mft\vceencoder\H264AsyncEncoderMFT.cpp(527):OnSetOutputType(4): failed to set MF_MT_FRAME_RATE set to 30000/1001, HRESULT(0x80070057)

**Comment by tuffee88** [comment]
Hmm,did you try to run this without the AMDh264Encoder present (any screen capture tools that might use it)?

**Comment by mxthewarrior** [comment]
How could i turn off the AMDh264Encoder? Im no using a screen capture tool, maeby is in the driver.
The actual state is: I tried 4 or 5 driver version and no changes, but, i follow the nexus post "Performance Boost (Plus optional FP Regen)" and now im testing the game without shadows, without grass and withoud LOD.
And also do this:
"﻿D. Edit this file using any text editor.
﻿﻿You can change "EffectsQuality", "VolumetricEffectQuality" and "RaytracingQuality" by changing the text between tags to "DISABLE"."
I test the game a few minutes and i didnt get the crash!

Here i have the log, i see way more "ERROR" but the game didnt close himself. Maeby the last "ERROR" list is because i close the game with alt+f4 d:
But i play the game like 30 minutes flawessly, i check that never go up 1940 mb of vram, so i think maeby is a vram problem.

the log:

00000001	0.00000000	[2344] Proxy Dll process attach	
00000002	0.00205680	[2344] D3D12CreateDevice-LoadLibrary Result:65bd0000	
00000003	0.40778199	[2344] Shutdown handler: initalize.	
00000004	0.67033839	[2344] D3D12CreateDevice - Proxy function called!	
00000005	0.67035568	[2344] D3D12CreateDevice - Original function address queried	
00000006	0.85615319	[12844] [TRACE] The DiagOutputDir folder is accessible 	
00000007	0.87604952	[2344] D3D12CreateDevice-CallResult:0	
00000008	1.29105961	[12516] [TRACE] The DiagOutputDir folder is accessible 	
00000009	2.13852715	[12844] Unexpected State	
00000010	2.17046928	[12844] Unexpected State	
00000011	2.51187325	[9524] ************Executable file path is: '	
00000012	2.51189685	[9524] \Device\HarddiskVolume3\Windows\System32\svchost.exe	
00000013	2.51191807	[9524] 	
00000014	2.51194048	[9524] PID=9524	
00000015	2.51196241	[9524] 	
00000016	2.51198292	[9524] ************Trace & dump config file path is: '	
00000017	2.51200366	[9524] C:\Users\boade\AppData\Local\AMDh264Encoder.cfg	
00000018	2.51202369	[9524] '************	
00000019	2.94711208	[9524] 2022-03-14 19:26:05.990     2434 [AMFH264AsyncEncoderMF]   Error: ..\..\..\..\..\runtime\src\mft\vceencoder\H264AsyncEncoderMFT.cpp(527):OnSetOutputType(0): failed to set MF_MT_FRAME_RATE set to 30000/1001, HRESULT(0x80070057) 	
00000020	5.68933058	[7156] Local Device Found	
00000021	5.68933058	[7156]   type: 045e 02a1	
00000022	5.68933058	[7156]   path: sdl://1	
00000023	5.68933058	[7156]   serial_number:  - 0	
00000024	5.68948936	[7156]   Manufacturer: 	
00000025	5.68951464	[7156]   Product:      XInput Controller	
00000026	5.68958378	[7156]   Release:      0	
00000027	5.68966103	[7156]   Interface:    -1	
00000028	5.68966103	[7156] 	
00000029	5.69009256	[7156] !! Steam controller device opened for index 0.	
00000030	6.45197296	[9524] 2022-03-14 19:26:09.495      868 [AMFH264AsyncEncoderMF]   Error: ..\..\..\..\..\runtime\src\mft\vceencoder\H264AsyncEncoderMFT.cpp(527):OnSetOutputType(1): failed to set MF_MT_FRAME_RATE set to 30000/1001, HRESULT(0x80070057) 	
00000031	8.64392090	[9524] 2022-03-14 19:26:11.688      868 [AMFH264AsyncEncoderMF]   Error: ..\..\..\..\..\runtime\src\mft\vceencoder\H264AsyncEncoderMFT.cpp(527):OnSetOutputType(2): failed to set MF_MT_FRAME_RATE set to 30000/1001, HRESULT(0x80070057) 	
00000032	9.56377697	[9524] 2022-03-14 19:26:12.607      868 [AMFH264AsyncEncoderMF]   Error: ..\..\..\..\..\runtime\src\mft\vceencoder\H264AsyncEncoderMFT.cpp(527):OnSetOutputType(3): failed to set MF_MT_FRAME_RATE set to 30000/1001, HRESULT(0x80070057) 	
00000033	10.51500320	[9524] 2022-03-14 19:26:13.559     31F0 [AMFH264AsyncEncoderMF]   Error: ..\..\..\..\..\runtime\src\mft\vceencoder\H264AsyncEncoderMFT.cpp(527):OnSetOutputType(4): failed to set MF_MT_FRAME_RATE set to 30000/1001, HRESULT(0x80070057) 	
00000034	13.00863934	[9524] 2022-03-14 19:26:16.052     31F0 [AMFH264AsyncEncoderMF]   Error: ..\..\..\..\..\runtime\src\mft\vceencoder\H264AsyncEncoderMFT.cpp(527):OnSetOutputType(5): failed to set MF_MT_FRAME_RATE set to 30000/1001, HRESULT(0x80070057) 	
00000035	16.35849380	[12252] "2022-03-14-19:26:19.402 ~~ Registry changed detected."	
00000036	16.41566086	[12252] title:  "RADEON SOFTWARE"	
00000037	16.41664696	[12252] text:  "Presiona %1 para abrir"	
00000038	16.41701889	[12252] hotkey:  "ALT+R"	
00000039	17.06279182	[12252] "2022-03-14-19:26:20.106 ~~ Failed to send bitmapchanged event, could not find handle"	
00000040	17.17179108	[12252] "2022-03-14-19:26:20.215 ~~ amddvr.exe is not running; exiting..."	
00000041	17.17194176	[12252] OverlaySourceWindow exitHandler	
00000042	17.18898201	[12252] QThread: Destroyed while thread is still running	
00000043	46.83942413	[8548] [0314/192649.883:ERROR:filesystem_win.cc(130)] GetFileAttributes C:\Users\boade\AppData\Local\Google\Chrome\User Data\Crashpad\attachments\6fbae451-1f68-4938-bd2d-91347da3f6b0: El sistema no puede encontrar el archivo especificado. (0x2)	
00000044	46.83977127	[8548] [0314/192649.883:ERROR:filesystem_win.cc(130)] GetFileAttributes C:\Users\boade\AppData\Local\Google\Chrome\User Data\Crashpad\attachments\77c441a9-f8d1-4809-bcc4-42b9802c93fe: El sistema no puede encontrar el archivo especificado. (0x2)	
00000045	46.84017944	[8548] [0314/192649.884:ERROR:filesystem_win.cc(130)] GetFileAttributes C:\Users\boade\AppData\Local\Google\Chrome\User Data\Crashpad\attachments\ecd58926-d63b-40fc-8281-d1d0f8f664e0: El sistema no puede encontrar el archivo especificado. (0x2)	
00000046	46.84043884	[8548] [0314/192649.884:ERROR:filesystem_win.cc(130)] GetFileAttributes C:\Users\boade\AppData\Local\Google\Chrome\User Data\Crashpad\attachments\66a4c391-cc2c-4e6a-bcb6-89e3b640e896: El sistema no puede encontrar el archivo especificado. (0x2)	
00000047	46.84064484	[8548] [0314/192649.884:ERROR:filesystem_win.cc(130)] GetFileAttributes C:\Users\boade\AppData\Local\Google\Chrome\User Data\Crashpad\attachments\15dac6dd-78a1-4e40-ae90-2834a59b2df4: El sistema no puede encontrar el archivo especificado. (0x2)	
00000048	46.84084702	[8548] [0314/192649.884:ERROR:filesystem_win.cc(130)] GetFileAttributes C:\Users\boade\AppData\Local\Google\Chrome\User Data\Crashpad\attachments\1149a51c-124e-464e-b15f-19f681e7fb96: El sistema no puede encontrar el archivo especificado. (0x2)	
00000049	946.85522461	[8548] [0314/194149.898:ERROR:filesystem_win.cc(130)] GetFileAttributes C:\Users\boade\AppData\Local\Google\Chrome\User Data\Crashpad\attachments\6fbae451-1f68-4938-bd2d-91347da3f6b0: El sistema no puede encontrar el archivo especificado. (0x2)	
00000050	946.85583496	[8548] [0314/194149.899:ERROR:filesystem_win.cc(130)] GetFileAttributes C:\Users\boade\AppData\Local\Google\Chrome\User Data\Crashpad\attachments\77c441a9-f8d1-4809-bcc4-42b9802c93fe: El sistema no puede encontrar el archivo especificado. (0x2)	
00000051	946.85614014	[8548] [0314/194149.899:ERROR:filesystem_win.cc(130)] GetFileAttributes C:\Users\boade\AppData\Local\Google\Chrome\User Data\Crashpad\attachments\ecd58926-d63b-40fc-8281-d1d0f8f664e0: El sistema no puede encontrar el archivo especificado. (0x2)	
00000052	946.85687256	[8548] [0314/194149.900:ERROR:filesystem_win.cc(130)] GetFileAttributes C:\Users\boade\AppData\Local\Google\Chrome\User Data\Crashpad\attachments\66a4c391-cc2c-4e6a-bcb6-89e3b640e896: El sistema no puede encontrar el archivo especificado. (0x2)	
00000053	946.85705566	[8548] [0314/194149.900:ERROR:filesystem_win.cc(130)] GetFileAttributes C:\Users\boade\AppData\Local\Google\Chrome\User Data\Crashpad\attachments\15dac6dd-78a1-4e40-ae90-2834a59b2df4: El sistema no puede encontrar el archivo especificado. (0x2)	
00000054	946.85748291	[8548] [0314/194149.901:ERROR:filesystem_win.cc(130)] GetFileAttributes C:\Users\boade\AppData\Local\Google\Chrome\User Data\Crashpad\attachments\1149a51c-124e-464e-b15f-19f681e7fb96: El sistema no puede encontrar el archivo especificado. (0x2)	
00000055	1068.57958984	[2344] Shutdown handler: cleanup.	
00000056	1068.58129883	[2344] Proxy Dll process detach

**Comment by mxthewarrior** [comment]
Well, i desactivated the xbox game bar and now my log is completly different, but this time i close the game normally.

00000013	51.23847198	[3220] Proxy Dll process attach	
00000014	51.24003601	[3220] D3D12CreateDevice-LoadLibrary Result:dabd0000	
00000015	51.56465149	[3220] Shutdown handler: initalize.	
00000016	51.71853256	[3220] D3D12CreateDevice - Proxy function called!	
00000017	51.71854782	[3220] D3D12CreateDevice - Original function address queried	
00000018	52.01594162	[3220] D3D12CreateDevice-CallResult:0	
00000019	71.92415619	[7320] ADLDirty = true	
00000020	72.25682831	[5356] [0314/202003.592:INFO:crash_reporting.cc(246)] Crash reporting enabled for process: gpu-process	
00000021	260.96560669	[7320] ADLDirty = false	
00000022	261.82354736	[7320] calling Gameperformance Runtime preload	
00000023	261.82507324	[7320] WARNING: QApplication was not created in the main() thread.	
00000024	261.96685791	[7320] QtWebEngine::initialize() called with QCoreApplication object already created and should be call before. This is depreciated and may fail in the future.	
00000025	263.11639404	[7320] QString::arg: 1 argument(s) missing in %1 detectó la presencia de uno o más paneles con valores altos de DPI conectados al sistema. Si se activa % 2, la resolución aumentará y se podrá personalizar la configuración de DPI.	
00000026	263.80545044	[7320] qml: RSX is here!	
00000027	263.82315063	[7320] qt.scenegraph.general: windows render loop	
00000028	263.82321167	[7320] qt.scenegraph.general: Using sg animation driver	
00000029	263.82327271	[7320] qt.scenegraph.general: Animation Driver: using vsync: 16.67 ms	
00000030	263.83746338	[7320] qt.scenegraph.general: opengl texture atlas dimensions: 512x512	
00000031	263.83755493	[7320] qt.scenegraph.general: R/G/B/A Buffers:   8 8 8 8	
00000032	263.83764648	[7320] qt.scenegraph.general: Depth Buffer:      24	
00000033	263.83770752	[7320] qt.scenegraph.general: Stencil Buffer:    8	
00000034	263.83773804	[7320] qt.scenegraph.general: Samples:           0	
00000035	263.83779907	[7320] qt.scenegraph.general: GL_VENDOR:         Google Inc.	
00000036	263.83782959	[7320] qt.scenegraph.general: GL_RENDERER:       ANGLE (AMD Radeon (TM) R7 370 Series Direct3D11 vs_5_0 ps_5_0)	
00000037	263.83786011	[7320] qt.scenegraph.general: GL_VERSION:        OpenGL ES 3.0 (ANGLE 2.1.0.57ea533f79a7)	
00000038	263.83798218	[7320] qt.scenegraph.general: GL_EXTENSIONS:     GL_ANGLE_client_arrays GL_ANGLE_depth_texture GL_ANGLE_framebuffer_blit GL_ANGLE_framebuffer_multisample GL_ANGLE_instanced_arrays GL_ANGLE_lossy_etc_decode GL_ANGLE_multiview GL_ANGLE_pack_reverse_row_order GL_ANGLE_program_cache_control GL_ANGLE_request_extension GL_ANGLE_robust_client_memory GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ANGLE_texture_usage GL_ANGLE_translated_shader_source GL_CHROMIUM_bind_generates_resource GL_CHROMIUM_bind_uniform_location GL_CHROMIUM_color_buffer_float_rgb GL_CHROMIUM_color_buffer_float_rgba GL_CHROMIUM_copy_compressed_texture GL_CHROMIUM_copy_texture GL_CHROMIUM_sync_query GL_EXT_blend_minmax GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_disjoint_timer_query GL_EXT_draw_buffers GL_EXT_frag_depth GL_EXT_map_buffer_range GL_EXT_occlusion_query_boolean GL_EXT_read_format_bgra GL_EXT_robustness GL_EXT_sRGB GL_EXT_shader_texture_lod GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_s3tc_srgb GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_texture_norm16 GL_EXT_texture_rg GL_EXT_texture_storage GL_EXT_unpack_subimage GL_KHR_debug GL_NV_EGL_stream_consumer_external GL_NV_fence GL_NV_pack_subimage GL_NV_pixel_buffer_object GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth32 GL_OES_element_index_uint GL_OES_get_program_binary GL_OES_mapbuffer GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_surfaceless_context GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_array_object	
00000039	263.83801270	[7320] qt.scenegraph.general: Max Texture Size: 16384	
00000040	263.83804321	[7320] qt.scenegraph.general: Debug context:    false	
00000041	263.86801147	[7320] QWindowsWindow::setGeometry: Unable to set geometry 160x100+603+289 (frame: 160x100+603+289) on PreloadWindow_QMLTYPE_240/"" on "\\.\DISPLAY1". Resulting geometry: 176x139+595+258 (frame: 176x139+595+258) margins: 0, 0, 0, 0)	
00000042	264.13415527	[7320] qrc:/Qml/RSX/Common/Animation/LongNumberAnimation.qml:18: ReferenceError: animationScale is not defined	
00000043	264.13415527	[7320] qrc:/Qml/RSX/Common/Animation/LongOpacityAnimator.qml:18: ReferenceError: animationScale is not defined	
00000044	264.13418579	[7320] qrc:/Qml/RSX/Common/CustomScrollView.qml:37: TypeError: Cannot read property 'maxWindowWidth' of undefined	
00000045	264.39196777	[6780] SetProcessDPIAwareness failed. (Acceso denegado.)	
00000046	264.40240479	[7320] qrc:/Qml/RSX/Common/CustomScrollView.qml:37: TypeError: Cannot read property 'maxWindowWidth' of undefined	
00000047	264.40313721	[7320] qrc:/Qml/RSX/Common/CustomScrollView.qml:37: TypeError: Cannot read property 'maxWindowWidth' of undefined	
00000048	264.41146851	[7320] qt.scenegraph.general: opengl texture atlas dimensions: 512x512	
00000049	264.41741943	[7320] qt.scenegraph.general: opengl texture atlas dimensions: 2048x1024	
00000050	264.81283569	[7320] SubscribeToAthenaForODProfiles	
00000051	265.14233398	[7320] qt.scenegraph.general: animation driver switched to timer mode	
00000052	852.45037842	[3220] Shutdown handler: cleanup.	
00000053	852.50421143	[3220] Proxy Dll process detach

**Comment by tuffee88** [comment]
Hmm, this looks good to me. Did you close the Game normally or did it crash ?

 If it's working for you (with reduced settings) please close this issue.

**Comment by mxthewarrior** [comment]
In the first i do alt+f4, in second i close the game normally.
I have some crash but its playable, so, thank you again ^^
