### ISSUE TITLE
help for the clueless

### ISSUE THREAD

**Issue by omgiknownothing** [tuffee88/d3d12ProxyEdrDx11_0#23]
not an issue, i just have no idea what im doing. not sure how to get the "fake" dll file. is there a way to just download it ?

**Comment by ShulsX** [comment]
Go to **Code** and you should see a section on the right that says **Releases**, click on it and it should take you to the downloads.

**Comment by tuffee88** [comment]
As this seems to come up rather frequently:

You can find the newest releases at: 
https://github.com/tuffee88/d3d12ProxyEdrDx11_0/releases

I'll add this to the README.
