### ISSUE TITLE
Assassin's Creed Valhalla: Crash after the splash screen

### ISSUE THREAD

**Issue by KellyFoxs1** [tuffee88/d3d12ProxyEdrDx11_0#25]
Crashes after the first splash screen. It just crashes without an error with a white screen. I'm not the only one with this error, and other people also flies out with this reason .  If the Elden Ring is all right with me .

**Comment by tuffee88** [comment]
Sorry, definitely works for some people though. 
What graphics card are you using ?  
Did you try all the usual stuff (windows + driver updates, disable overlays and overclocking, ecc.) ?

Please also try to run this with vkd3d-proton (see README)

**Comment by KellyFoxs1** [comment]
I have no overclocking, and also it does not run on a friend's 740 and I have a 750 4 gb. Similar situation ...Both of them. Eden Ring goes well though... 
My pc is not overclocked etc...I will try the proton, thanks . Although Windows is updated, as well as drivers ... After the introductory video we crashed ...

**Comment by tuffee88** [comment]
Please let me know if this works for you with vkd3d-proton.

**Comment by tuffee88** [comment]
Just had a look - depending on settings I do get past the plash screen, but crash (at the end of the intro sequence).
Testing with vkd3d-proton didn't help (game won't launch at all).

-> Sorry, but as there is not straightforward indication as WHY the crash occurs I'll won't be able to fix this.

I'll add a note for other players in the README about this.
