### ISSUE TITLE
Game crashes after a few minutes of gameplay in Assassin's Creed Valhalla on GTX 750ti

### ISSUE THREAD

**Issue by YRS111** [tuffee88/d3d12ProxyEdrDx11_0#26]
i know it's too much to ask but...do you think you can fix it?

**Comment by tuffee88** [comment]
There's probably not mucht that I can do about this. 
I'll try to get a copy of Assassin's Creed Valhalla and have a look if I can reproduce this with my graphics card.

**Comment by tuffee88** [comment]
Just had a look: Similar behaviour on my Nvidia Kepler card (with newest Game-Ready drivers).
I don't see an obvious reason for crashing (also seems to vary how long until the crash) - sorry, but I won't be able to fix this.

-> Added a note in the README to inform other players about this.

**Comment by YRS111** [comment]
Thank you you for checking my issue. I hope that all of us would be able to
play this game
