### ISSUE TITLE
It's not working after updating game to new patches. 

### ISSUE THREAD

**Issue by Shippdenn** [tuffee88/d3d12ProxyEdrDx11_0#27]
Hello, This fix was working on patch 1.02.1 and i could play the game But after installing patch 1.02.2 it does not work anymore, the game loads and it stays on white screen ! it doesn't crash, it doesn't freeze, it doesn't give me error, it doesn't use CPU/GPU/Memory ( just a little it uses) !!!
I tried to fix it with installing patch 1.02.3 but it doesn't work neither.

I tried to debug as you said and this is what happend, 

**1. First time The game didn't even launch** : 

00000001	0.00000000	[3392] Proxy Dll process attach	
00000002	0.00099600	[3392] D3D12CreateDevice-LoadLibrary Result:6b6f0000	
00000003	0.33997241	[3392] Proxy Dll process detach	
00000004	11.07236862	[6148] [0312/214004.012:INFO:crash_reporting.cc(246)] Crash reporting enabled for process: utility	
00000005	15.32814217	[2316] [0312/214008.267:INFO:CONSOLE(14)] "Uncaught TypeError: Cannot read property 'BIsDirty' of undefined", source: https://community.akamai.steamstatic.com/public/javascript/applications/community/events.js?contenthash=d55ba231ab7e2b29e6cd (14)	
00000006	19.56283760	[7780] DLL_PROCESS_DETACH	
00000007	19.57291603	[7780] DetourDetach MyPresentD10D11	
00000008	19.57310677	[7780] DLL_PROCESS_DETACH END	
00000009	44.26961517	[7308] TrueD3D11CreateDeviceAndSwapChain found	
00000010	44.27523041	[7308] TruePresentD10D11 is [6e2ae270]	
00000011	44.62505722	[7308] DetourTransactionCommit ok	
00000012	44.62604141	[7308] TruePresentD10D11 is [6db40060]	

**2. The game launched** :

00000001	0.00000000	[1408] Proxy Dll process attach	
00000002	0.00108290	[1408] D3D12CreateDevice-LoadLibrary Result:812e0000	
00000003	0.30323350	[1408] Shutdown handler: initalize.	
00000004	0.38125730	[1408] D3D12CreateDevice - Proxy function called!	
00000005	0.38131550	[1408] D3D12CreateDevice - Original function address queried	
00000006	0.96636152	[1408] D3D12CreateDevice-CallResult:0	
00000007	30.97167969	[7780] TrueD3D11CreateDeviceAndSwapChain found	
00000008	30.97226524	[7780] TruePresentD10D11 is [6e2ae270]	
00000009	31.47529030	[7780] DetourTransactionCommit ok	
00000010	31.47592735	[7780] TruePresentD10D11 is [6db40060]

**Comment by tuffee88** [comment]
Works for me on the most recent Steam retail version (1.02.3). 
Are you using a different release ? You do definitedly get past D3D12 init so this is probably not directly related to this fix.

Do you have any Overlays, etc. active ?

**Comment by Shippdenn** [comment]
Umm I'm using a pirated version (DODI repacks)
as much as i know many people with pirated versions could play game with this fix. (maybe my file is broken). 

No, I've Upgraded my Windows to 10 last week so basically i don't have anything yet to be active. I just have steam which i don't use it when i launch the game. 

Maybe Microsoft's apps are doing something, How can i find the overlay/active apps ?

**Comment by tuffee88** [comment]
Steam or different screen capture tools f.e. - but if you have to ask about them you probably don't have anything special active that's causing this. So this is probably related to the cracked version you're using - sorry, I can't help you out with that.
