### ISSUE TITLE
Question about adapting this for other games

### ISSUE THREAD

**Issue by FatBouk** [tuffee88/d3d12ProxyEdrDx11_0#3]
Hey man, I'm really sorry for leaving this here, but github really doesn't have any other way to message other users.

Are you thinking about adapting this to other games that also have this limitation? I'm thinking of Death Stranding and God of War. They also require directx 12 ultimate, but they work just fine on DX11_0 gpus (death stranding had a fix that no longer works, and it ran on my gpu).

**Comment by tuffee88** [comment]
God of War and Death Stranding are likely different: They probably check the supported feature level and refuse to launch if the minimum feature level is not met. 

So even if they don't use any features > 11_0 it's not quite as simple as with Elden Ring (which doesn't perform any checks at all currently). To make this work I'd have to somehow spoof/modify the ID3D12Device that's used for capability querying (see https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12device-checkfeaturesupport) - or more likely patch the game executable to ignore the response or change vkd3d to do the same :-) 

So this would be a probably a bigger job, which I can't tackle now - but I'm interested in this and will probably check out God of War later this year (need to beat Elden Ring first !!!), so I'll keep this open as feature request.

**Comment by FatBouk** [comment]
Thank you for the quick reply. I'm currently playing elden ring on my 750ti without any problems thanks to you.

**Comment by tuffee88** [comment]
Glad to hear its working for you :thumbsup:

**Comment by FatBouk** [comment]
It just crashes to desktop with dxvk. I think that that it still checks somewhere for the feature level. Or it just doesn't work on my system.

**Comment by VCBorges** [comment]
i'm having 0xc0000142 Error, any thoughts?

**Comment by tuffee88** [comment]
Could be missing/corrupt dlls - did you copy the original d3d12.dll and d3d12core.dll to the game folder and rename d3d12.dll to d3d12_original.dll ?

**Comment by tuffee88** [comment]
Closing this one in favour of the other topics that have been opened for specific games :-)
