### ISSUE TITLE
does it work in combination with reshade?

### ISSUE THREAD

**Issue by Nerboruto** [tuffee88/d3d12ProxyEdrDx11_0#33]
I did some tests but I couldn't get it to work with the wrapper.
using dxgi.dll..

**Comment by tuffee88** [comment]
The newest release should :-) 
I changed the hooking to (hopefully) play nicer with other tools that mess with D3D12*

-> At least on my PC I can access the ReShade menu now (only when you remove d3d12_original.dll from the game folder-> ReShade really likes to hook system32/d3d12.dll so we have to use this one too)

**Comment by Nerboruto** [comment]
thanks I'll try it ...
