### ISSUE TITLE
999 Green Box Stacking error since 17/03/2022 patch

### ISSUE THREAD

**Issue by SunnyBloop** [tuffee88/d3d12ProxyEdrDx11_0#34]
Recently been getting a graphical error where a number of green boxes stacked to 999 appear on the right side of the screen.

Seems to be an issue that's solved by re-enabling EAC and going online, however that's not possible for players using this fix (and the fix bypasses EAC and is required to actually load up the game to begin with).

Has anyone found a way to fix this? (Not sure if this is the right place to post this - has been posted on the reddit, but currently haven't seen a fix for people using the dll bypass.

![010250d17cd501430a9a3da5b46f53a3-jpg](https://user-images.githubusercontent.com/101893414/159061791-ebbe7bb7-b83d-4d00-b337-9b26de27e0cf.jpg)
)

**Comment by AmmonHepworth** [comment]
verifying my game files after the update and then renaming eldenring.exe again fixed the box stacking for me. The modded dll also stays in the folder just fine

**Comment by SunnyBloop** [comment]
Can confirm, deleting start_protected_game.exe (as well as all the d3d12.dll files to make sure) forcing Steam to verify it, then reapplying the fix solves the issue for me.

Definitely seems like a problem with EAC and start_protected_game. During the next update, I'll try and just delete start_protected_game.exe and remake it using the updated elden_ring.exe to see if that works as well.
