### ISSUE TITLE
Question about DX12 to DX11

### ISSUE THREAD

**Issue by TheApprentice6** [tuffee88/d3d12ProxyEdrDx11_0#4]
Hey, thank you so much for this amazing fix, have you seen this https://github.com/megai2/d912pxy dev made DX9 to DX12, and you made DX11 to DX12 proxy, do you think it would somehow be possible to make DX12 to DX11, make games like Elden Ring run on DX11, this would help a lot of people with Windows and older GPUs run and maybe with DXVK, I'm able to play this game on DX12 but VKD3D won't work for me for some reason. I'm sorry if this is a ridiculous question, but I'm really curious.

**Comment by tuffee88** [comment]
Thanks ! Just one small correction: Tbh this is not a DX11 to DX12 proxy - you'll need real D3D12 support for this to work, I just modify the min. required feature leavel that is used for device init/context creation. 

So if Elden Ring were to use any DX_FEATURE_LEVEL 11_1 or 12_0 features (that are not availabily as option on DX_FEATURE_LEVEL 11_0) this would crash and burn :-)

But back to your question: Creating a DX12 to DX11 wrapper is probably technically possible but would be major effort - DX12 is much more low level than DX11 so for something like this using Vulkan is a much better joice.

Btw. using vkd3d-proton with this seems to work - at least on Windows 7 (https://www.nexusmods.com/eldenring/mods/12)
