### ISSUE TITLE
Not working on older card

### ISSUE THREAD

**Issue by asda488** [tuffee88/d3d12ProxyEdrDx11_0#42]
Hi, I've tried using the latest version (0.3) and Elden Ring is still not launching, I suspect it is due to my card being very old - it is an [ATI Firepro V4800](https://www.techpowerup.com/gpu-specs/firepro-v4800.c572), which supports DirectX 11.2 with a feature version of 11.0, however I'm not too sure whether this is the exact case (the rest of my system: Windows 10, Intel Core i7-980, 16GB RAM). Please find attached some [logs](https://github.com/tuffee88/d3d12ProxyEdrDx11_0/files/8466102/log.LOG) from DebugView as well, (they do seem to be returning a DXGI_ERROR_UNSUPPORTED 0x887A0004). Finally, even if my card is too old, is there any possible way of playing it at all (wrappers for DX11 onto DX12 etc?)

Thank you, 
asda488.

**Comment by tuffee88** [comment]
As far as I know for TerraScale cards AMD doesn't support Vulkan nor DX12 (even if hardware support might be sufficient to write drivers for both APIs). In hindsight that's a big reason to buy Nvidia I guess.

I don't know of any DX11(or OpenGl) to DX12 wrappers, and software rendering (using WARP) will work but is usually unplayably slow.  Sorry, but this is not something that I can fix in this project :-(
