### ISSUE TITLE
Is it possible to alse put a D3D11.dll file besides your modification so it can use the mentioned DLL file? This could really help with bringing 3DVision to EdR thanks to 3DMigoto!

### ISSUE THREAD

**Issue by HydrargyrumGames** [tuffee88/d3d12ProxyEdrDx11_0#44]
Is it possible to alse put a D3D11.dll file besides your modification so it can use this DLL for it's calls?
 This could really help with bringing 3DVision to EdR thanks to 3DMigoto!

**Comment by tuffee88** [comment]
Hi [HydrargyrumGames](https://github.com/HydrargyrumGames),

I'm afraid but this won't work - with this proxy dll Elden Ring is still a DX12 game (it's just lowering the required hardware feature level to 11_0 - so it's bad naming overall)

**Comment by HydrargyrumGames** [comment]
Solved
