### ISSUE TITLE
dosen't work on hd6000(i5 5250u)

### ISSUE THREAD

**Issue by maskmark** [tuffee88/d3d12ProxyEdrDx11_0#49]
still WSOD. Is this never supposed to work on intel DX11 graphic cards?

**Comment by tuffee88** [comment]
Hi,
this is for DX12 graphics cards only (yeah, the feature level 11_0 naming is confusing) - given the feature requirements intel could probably have developed a dx12 driver for your card (like Nvidia did with the Maxwell and Kepler generation cards), but with the current state of things you're out of luck, sorry.
