### ISSUE TITLE
gtx 960m weird call result

### ISSUE THREAD

**Issue by Saya47** [tuffee88/d3d12ProxyEdrDx11_0#52]
Hello!
```
[11932] Proxy Dll process attach
[11932] D3D12CreateDevice - Loaded d3d12_original.dll
[11932] D3D12CreateDevice - LoadLibrary Result: 7ff862090000
[11932] Shutdown handler: initalize.
[11932] D3D12CreateDevice - DEBUG: Checking Pix support
[11932] D3D12CreateDevice - DEBUG: Attempt to load Pix support!
[11932] D3D12CreateDevice - DEBUG: Pix WinPixGpuCapturer.dll not found, no extended Pix support available
[11932] D3D12CreateDevice - Proxy function called!
[11932] D3D12CreateDevice - Original function address available
[11932] D3D12CreateDevice - CallResult: ffffffff80004002
[11932] D3D12CreateDevice - CallResult: ffffffff80004002
```
I can barely find anything on this error code, the only thing I found was this:
https://stackoverflow.com/questions/37046346/system-string-and-system-string-difference-in-c-sharp
Which means no interface??!

**Comment by tuffee88** [comment]
The returned result looks more like one of the more generic HRESULT codes and maps to the following:
E_NOINTERFACE | No such interface supported | 0x80004002

-> This is very likely not related to the Elden Ring DX12 Feature level requirement, please check that you do have the most recent Windows build/all updates installed + proper Nvidia GPU drivers and (as this is a notebook, right?) that your Nvidia GPU is actually used for rendering (selected as performance GPU, please check that this works for other games/apps).

**Comment by Saya47** [comment]
Hello thanks very much for responding, yes this is a notebook, and I do have the latest GPU drivers and the GPU is assigned for rendering Elden Ring in the Nvidia control panel, but I have to say, my Windows 10 build is old, I'm on winver 1803, I didn't know I need the latest Windows 10 build to run the game, because honestly, some people even ran the game on Window 7 and it worked fine for them. It's such a hassle and burden to update Windows, I'm kind of happy with this version, so I guess I have to install the latest version of Windows on another disk and test if it resolves the issue.
Thanks very much for helping and clarifying.

**Comment by tuffee88** [comment]
No worries, please let me know if this fixed the issues for you.

**Comment by Saya47** [comment]
Hello @tuffee88 I finally upgraded my Windows! after so many months! And now I'm on Winver 20H2 and the game works fine thanks to you DLL! Thank you for all the work and helps. Upgrading Windows was very hard but I had to do it finally xD
