### ISSUE TITLE
Dont work on w10 22 h2

### ISSUE THREAD

**Issue by nhfv** [tuffee88/d3d12ProxyEdrDx11_0#62]
960m... white screen - blac screen - crash without error ...
in game cursor visible before crash
win log: error in D3D12Core.dll
change Disable EasyAnti-Cheat - done
update: in win10 20h1 - work good
sorry my english

update 2: last video driver - work ok

**Comment by tuffee88** [comment]
Hi nhfv,

did you get Elden Ring working using the latest video driver on Windows 10 22h2 ?

I'll probably update my Windows install this weekend to and give this another try, but it would be nice to know that it's working for you.

Thanks,

**Comment by nhfv** [comment]
work with last driver. my close
