### ISSUE TITLE
TDR problem with r9 280x (Help for vulkan try)

### ISSUE THREAD

**Issue by Perceval-Muller** [tuffee88/d3d12ProxyEdrDx11_0#65]
Hi so your patch work fine for me (thanks a lot !) but I encounter tdr error (i tried many things but sometimes it is just unplayable (crash every 5 mins))

I wanted to try the optionnal solution (try it on vulkan) so i make the two optional step that you suggest (take original d3d12 from windows system32)

And then I don't really understand what I have to do on the nexus mod you refer to ? I download the .tar.zst from https://github.com/HansKristian-Work/vkd3d-proton/releases/tag/v2.3.1 and there is a d3d12.dll file, I rename it by d3d12_original and replace the old one (from windows) by it. But the game doesn't lunch anymore

Did I miss something ?

**Comment by tuffee88** [comment]
Hi,
sounds to me more like a driver issue - are you sure your GPU has decent Vulkan support on Windows ?

If you want to try Vulkan you just need to grab the d3d12.dll file from the vkd3d-proton release (like you mentioned), rename this one to d3d12_original.dll and place it in the Elden Ring folder (along with the d3d12.dll from this page).

In short you should have the following files in your Elden Ring folder:
d3d12.dll -> from this page
d3d12_original.dll -> from vkd3d-proton (renamed from d3d12.dll)

**Comment by Perceval-Muller** [comment]
Hi sorry for the late response. So I finnaly made it run on vulcan (I had to "patch alhpa" the file from nexus as it is said in it) Now the game run qwithout those tdr poroblems but i got lots of graphics issues (like rainbow, blue or red stone everywhere, sometimes it is my horse sometimes it something else) It made the game a bit unplayable actually so I will search another solutions for this 

Thanks for your help !

**Comment by tuffee88** [comment]
Thanks for the feedback, I'll close this as solved

**Comment by tuffee88** [comment]
Closing as the game does launch and run (albeit with graphical problems)
