### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by KrisVish** [tuffee88/d3d12ProxyEdrDx11_0#69]
Hi  Tuffee88

Please note I am an old aged person helping my grand daughter play spiderman remastered steam

The problem we are facing is it does not launch at all on win 10 x64 i7 pc and closes immediately

I saw your GitHub article about your solution to elden ring not launching and do not know if I can try your dx12.dll in spiderman remaster launching problem

Please advise with any other workaround to solve this  problem.   Please help

Thank You
Kris and family

[Marvel's Spider-Man Remastered.log](https://github.com/tuffee88/d3d12ProxyEdrDx11_0/files/14227316/Marvel.s.Spider-Man.Remastered.log)

**Comment by tuffee88** [comment]
Hi KrisVish,

unfortunatedly I won't be able to help you regarding Spiderman Remastered.

The issue with this game is not related to this fix for Elden ring (Spiderman Remastered is known to "work" with older DX12 FL 11_0 GPUs provided they have enough vram).

Best,
tuffee
