### ISSUE TITLE
AMD Radeon HD 5750 Issue on Elden Ring

### ISSUE THREAD

**Issue by adamk324** [tuffee88/d3d12ProxyEdrDx11_0#72]
tried Debug And RELEASE build debug got to this 
![elden ring](https://github.com/tuffee88/d3d12ProxyEdrDx11_0/assets/90887270/bd0160a6-1f73-4fad-aef0-56d28d4dd3c0)

**Comment by tuffee88** [comment]
Hi @adamk324,
are you sure that AMD provides DX 12 drivers for this card ? Please provide a report or screenshot from dxdiag so we can have a closer look.

**Comment by adamk324** [comment]
> Hi @adamk324,
> are you sure that AMD provides DX 12 drivers for this card ? Please provide a report or screenshot from dxdiag so we can have a closer look.
> 

No they dont. Isnnt this meant to be an DX 11 fix?

**Comment by tuffee88** [comment]
Hi @adamk324,

sorry, this is a DX12 only fix (for DX12 cards that support only Feature Level 11 - I know it's kinda confusing).
